# Nhân ma trận với vecto dùng toán tử @ (A * B = A @ B)


In [10]:
import numpy as np
A = np.array([[1, 2], [4, 5], [6, 7]])
B = np.array([1, 1])
print(f'A * B = {A @ B}')

A * B = [ 3  9 13]


Để nhân 2 ma trận A * B thì số cột của ma trận 1 phải bằng số hàng của ma trận 2 (nA = mB)
Chúng ta nhân 2 ma trận bằng cách tách 1 ma trận ra rồi các vecto rồi nhân sau đó ghép lại

In [14]:

A = np.array([[1, 2, 3], [4, 5, 6], [1, 5, 9]])
B = np.array([[1, 3], [4, 5], [6, 8]])
print(f'A * B = {A@B}')

A * B = [[ 27  37]
 [ 60  85]
 [ 75 100]]


                                Identity matrix (ma trận đơn vị)

Identity matrix là ma trận mà khi nhân với bất kì ma trận khác cùng kích thước, ma trận đó sẽ không đổi. Phép nhân với identity matrix có tính chất giao hoán. Chúng ta có thể xem identity matrix là “số 1” của ma trận.

Cấu trúc của identity matrix là 1 ma trận có số 1 trên đường chéo.

In [17]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Phép nhân “element-wise” với ma trận
Đối với phép nhân element-wise, kết quả sẽ là một ma trận với những phần tử là tích của các phần tử là tích của 2 phần tử tương ứng trong 2 ma trận.

In [19]:
_a = [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]
_b = [ [ 2, 3, 5], [7, 9, 21] ]
a = np.array(_a) #create 2 * 3 matrix: a
b = np.array(_b) #create 2 * 3 matrix: b
print('a .* b:', a * b) #print out a .* b

a .* b: [[  2   6  15]
 [ 28  45 126]]


Toán tử logic với ma trận

In [20]:
import numpy as np
a = np.eye(5)
print(a == 1)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


# Inverse matrix (ma trận khả nghịch)

Inverse matrix được kí hiệu bằng: A-1

Tích của ma trận với ma trận đảo của nó sẽ là một Identity matrix.

Tương tự như trong số tự nhiên: 2 * 2-1 = 1

Với NumPy function dùng để invert matrix là:

   np.linalg.pinv(matrix)

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.linalg.pinv(A)
print(f'A * B{A @ B}')

A * B[[ 1.00000000e+00  3.05311332e-16]
 [-4.44089210e-16  1.00000000e+00]]


Transpose matrix được kí hiệu là: $A^T$

Transpose matrix là ma trận đảo hàng và cột so với ma trận gốc.

Với NumPy ta sử dụng function np.transpose() để transpose matrix.

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.transpose(A)
print (B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Hàm size với ma trận

Chúng ta có thể sử dụng hàm size để lấy kích thước của ma trận:

np.size(matrix, axis)

Trong đó:

matrix: ma trận cần tìm kích thước

axis: chiều, nếu là 0 sẽ trả về số hàng, 1 trả về số cột, mặc định trả về số phần tử.

In [28]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.size(A,0)
print(B)

3


# Hàm sum và max/min với ma trận

Chúng ta có thể sử dụng hàm sum để lấy tổng các phần tử, max để lấy phần tử lớn nhất, min để lấy phần tử nhỏ nhất.

Cấu trúc:

np.sum(matrix,axis)

np.max(matrix,axis)

np.min(matrix,axis)

Trong đó

matrix: ma trận cần tìm kích thước

axis: chiều, nếu là 0 sẽ tính theo cột, 1 sẽ tính theo hàng, mặc định sẽ tính trên cả ma trận.

In [30]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.sum(A, 0)
print(B)

[12 15 18]
